### ISSUE TITLE
PyperclipException

### ISSUE THREAD

**Issue by StefanYohansson** [skorokithakis/bakeit#2]
Hi @skorokithakis ,

I'm getting this Exception when running `bakeit`.

System: Arch Linux x64 (ApricityOS)
Interface: Gnome 3
Terminal: gnome-terminal

```shell
$ echo "hi" | python bakeit/cli.py
Paste URL: https://www.pastery.net/zfeckh/
Traceback (most recent call last):
  File "bakeit/cli.py", line 90, in <module>
    main()
  File "bakeit/cli.py", line 84, in main
    pyperclip.copy(url)
  File "/usr/lib/python3.5/site-packages/pyperclip/clipboards.py", line 125, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.exceptions.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.org 
```

**Comment by skorokithakis** [comment]
Hah, I saw the ticket and fixed it before noticing your PR, sorry about that. Please use 0.2.1 and thanks for the report!
